spring:
  application:
    name: flight-status-api
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
  data:
    redis:
      password: ${REDIS_PASSWORD}
      username: ${REDIS_USER}
      port: ${REDIS_PORT}
      host: ${REDIS_HOST}
