
CREATE TABLE IF NOT EXISTS flight
(
    id          BIGINT       NOT NULL,
    arrival     TIMESTAMPTZ  NOT NULL,
    departure   TIMESTAMPTZ  NOT NULL,
    destination VARCHAR(256) NOT NULL,
    status      VARCHAR(255) NOT NULL,
    origin      VARCHAR(256) NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT flight_status_check CHECK (status IN ('IN_TIME', 'DELAYED', 'CANCELLED'))
);


CREATE SEQUENCE IF NOT EXISTS flight_seq
    INCREMENT BY 50;


CREATE INDEX IF NOT EXISTS idx6v7b69ncta2pvremitd084wpq
    ON flight (arrival);

CREATE INDEX IF NOT EXISTS idx9lxn5gkatc6t14vovlnugm8j0
    ON flight (origin, arrival);

CREATE INDEX IF NOT EXISTS idxtfs9ytexl1f6gsilcsjk4vcf8
    ON flight (destination, arrival);

CREATE INDEX IF NOT EXISTS idxfa86q39s9xlhdlb8k66qc9d1j
    ON flight (origin, destination, arrival);


CREATE TABLE IF NOT EXISTS roles
(
    id   SERIAL PRIMARY KEY,
    code VARCHAR(256) NOT NULL,
    CONSTRAINT ukch1113horj4qr56f91omojv8 UNIQUE (code)
);


CREATE TABLE IF NOT EXISTS users
(
    id       BIGINT       NOT NULL,
    password VARCHAR(256) NOT NULL,
    username VARCHAR(256) NOT NULL,
    role_id  INTEGER      NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT ukr43af9ap4edm43mmtq01oddj6 UNIQUE (username),
    CONSTRAINT fkp56c1712k691lhsyewcssf40f FOREIGN KEY (role_id) REFERENCES roles (id)
);


CREATE SEQUENCE IF NOT EXISTS users_seq
    INCREMENT BY 50;


CREATE TABLE IF NOT EXISTS refresh_token
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY,
    expires_at TIMESTAMPTZ,
    is_revoked BOOLEAN DEFAULT false,
    issued_at  TIMESTAMPTZ,
    token      VARCHAR(1000),
    user_id    BIGINT,
    PRIMARY KEY (id),
    CONSTRAINT ukr4k4edos30bx9neoq81mdvwph UNIQUE (token),
    CONSTRAINT fkjtx87i0jvq2svedphegvdwcuy FOREIGN KEY (user_id) REFERENCES users (id)
);


CREATE INDEX IF NOT EXISTS idxr43af9ap4edm43mmtq01oddj6
    ON users (username);