create table flight
(
    id          bigint                      not null,
    arrival     timestamp(6) with time zone not null,
    departure   timestamp(6) with time zone not null,
    destination varchar(256)                not null,
    status      varchar(255)                not null,
    origin      varchar(256)                not null,
    primary key (id),
    constraint flight_status_check
        check (status IN ('IN_TIME', 'DELAYED', 'CANCELED'))
);

create sequence flight_seq
    increment by 50;

create index idx6v7b69ncta2pvremitd084wpq
    on flight (arrival);

create index idx9lxn5gkatc6t14vovlnugm8j0
    on flight (origin, arrival);

create index idxtfs9ytexl1f6gsilcsjk4vcf8
    on flight (destination, arrival);

create index idxfa86q39s9xlhdlb8k66qc9d1j
    on flight (origin, destination, arrival);

create table roles
(
    id   integer      not null,
    code varchar(256) not null,
    primary key (id),
    constraint ukch1113horj4qr56f91omojv8
        unique (code)
);

create table users
(
    id       bigint       not null,
    password varchar(256) not null,
    username varchar(256) not null,
    role_id  integer      not null,
    primary key (id),
    constraint ukr43af9ap4edm43mmtq01oddj6
        unique (username),
    constraint fkp56c1712k691lhsyewcssf40f
        foreign key (role_id) references roles
);

create sequence users_seq
    increment by 50;

create table refresh_token
(
    id         bigint generated by default as identity,
    expires_at timestamp(6) with time zone,
    is_revoked boolean default false,
    issued_at  timestamp(6) with time zone,
    token      varchar(1000),
    user_id    bigint,
    primary key (id),
    constraint ukr4k4edos30bx9neoq81mdvwph
        unique (token),
    constraint fkjtx87i0jvq2svedphegvdwcuy
        foreign key (user_id) references users
);

create index idxr43af9ap4edm43mmtq01oddj6
    on users (username);

